// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: attending.sql

package database

import (
	"context"

	"github.com/google/uuid"
)

const addGoing = `-- name: AddGoing :exec
INSERT INTO users_events (user_id, event_id)
VALUES (
    $1,
    $2
)
`

type AddGoingParams struct {
	UserID  uuid.UUID
	EventID uuid.UUID
}

func (q *Queries) AddGoing(ctx context.Context, arg AddGoingParams) error {
	_, err := q.db.ExecContext(ctx, addGoing, arg.UserID, arg.EventID)
	return err
}

const removeGoing = `-- name: RemoveGoing :exec
DELETE FROM users_events
WHERE user_id = $1 AND event_id = $2
`

type RemoveGoingParams struct {
	UserID  uuid.UUID
	EventID uuid.UUID
}

func (q *Queries) RemoveGoing(ctx context.Context, arg RemoveGoingParams) error {
	_, err := q.db.ExecContext(ctx, removeGoing, arg.UserID, arg.EventID)
	return err
}
