// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: friends.sql

package database

import (
	"context"

	"github.com/google/uuid"
)

const addFriend = `-- name: AddFriend :exec
INSERT INTO friends (requester_id, requestee_id, requested)
VALUES (
    requester_id = $1,
    requestee_id = $2,
    requested = NOW()
)
`

type AddFriendParams struct {
	RequesterID uuid.UUID
	RequesteeID uuid.UUID
}

func (q *Queries) AddFriend(ctx context.Context, arg AddFriendParams) error {
	_, err := q.db.ExecContext(ctx, addFriend, arg.RequesterID, arg.RequesteeID)
	return err
}

const confirmFriend = `-- name: ConfirmFriend :exec
UPDATE friends
SET confirmed = NOW()
WHERE requester_id = $2 AND requestee_id = $1
`

type ConfirmFriendParams struct {
	RequesteeID uuid.UUID
	RequesterID uuid.UUID
}

func (q *Queries) ConfirmFriend(ctx context.Context, arg ConfirmFriendParams) error {
	_, err := q.db.ExecContext(ctx, confirmFriend, arg.RequesteeID, arg.RequesterID)
	return err
}

const getUserFriends = `-- name: GetUserFriends :many
SELECT u.id, u.first_name, u.last_name, u.dob, u.created_at, u.updated_at, u.email, u.hased_password
FROM users AS u
INNER JOIN friends AS f
ON (u.id = f.requester_id AND f.requestee_id = $1)
OR (u.id = f.requestee_id AND f.requester_id = $1)
WHERE confirmed IS NOT NULL
ORDER BY u.first_name ASC
`

func (q *Queries) GetUserFriends(ctx context.Context, requesteeID uuid.UUID) ([]User, error) {
	rows, err := q.db.QueryContext(ctx, getUserFriends, requesteeID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []User
	for rows.Next() {
		var i User
		if err := rows.Scan(
			&i.ID,
			&i.FirstName,
			&i.LastName,
			&i.Dob,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Email,
			&i.HasedPassword,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
