// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package database

import (
	"database/sql"
	"time"

	"github.com/google/uuid"
)

type Post struct {
	ID        uuid.UUID
	CreatedAt time.Time
	UpdatedAt time.Time
	Body      string
	UserID    uuid.UUID
}

type User struct {
	ID            uuid.UUID
	FirstName     string
	LastName      sql.NullString
	Dob           sql.NullTime
	CreatedAt     time.Time
	UpdatedAt     time.Time
	Email         string
	HasedPassword string
}
