// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package database

import (
	"database/sql"
	"time"

	"github.com/google/uuid"
)

type Ally struct {
	RequesterID uuid.UUID
	RequesteeID uuid.UUID
	Requested   time.Time
	Confirmed   sql.NullTime
}

type Event struct {
	ID          uuid.UUID
	Name        string
	Location    sql.NullString
	Date        time.Time
	CreatedAt   time.Time
	UpdatedAt   time.Time
	Description sql.NullString
	GroupID     uuid.UUID
	Slug        string
}

type Group struct {
	ID          uuid.UUID
	Name        string
	CreatedAt   time.Time
	UpdatedAt   time.Time
	AdminID     uuid.UUID
	Description sql.NullString
	Slug        string
}

type Post struct {
	ID        uuid.UUID
	CreatedAt time.Time
	UpdatedAt time.Time
	Body      string
	UserID    uuid.UUID
}

type RefreshToken struct {
	Token     string
	CreatedAt time.Time
	UpdatedAt time.Time
	UserID    uuid.UUID
	ExpiresAt time.Time
	RevokedAt sql.NullTime
}

type User struct {
	ID             uuid.UUID
	FirstName      string
	LastName       sql.NullString
	Dob            sql.NullTime
	CreatedAt      time.Time
	UpdatedAt      time.Time
	Email          string
	Slug           string
	HashedPassword string
}

type UsersGroup struct {
	UserID  uuid.UUID
	GroupID uuid.UUID
}
