// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: users.sql

package database

import (
	"context"
	"database/sql"

	"github.com/google/uuid"
)

const createUser = `-- name: CreateUser :one
INSERT INTO users (id, first_name, last_name, dob, created_at, updated_at, email, hased_password)
VALUES (
    gen_random_uuid(),
    $1,
    $2,
    $3,
    NOW(),
    NOW(),
    $4,
    $5
)
RETURNING id, first_name, last_name, dob, created_at, updated_at, email, hased_password
`

type CreateUserParams struct {
	FirstName     string
	LastName      sql.NullString
	Dob           sql.NullTime
	Email         string
	HasedPassword string
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (User, error) {
	row := q.db.QueryRowContext(ctx, createUser,
		arg.FirstName,
		arg.LastName,
		arg.Dob,
		arg.Email,
		arg.HasedPassword,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.FirstName,
		&i.LastName,
		&i.Dob,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Email,
		&i.HasedPassword,
	)
	return i, err
}

const getUserByEmail = `-- name: GetUserByEmail :one
SELECT id, first_name, last_name, dob, created_at, updated_at, email, hased_password
FROM users
WHERE email = $1
`

func (q *Queries) GetUserByEmail(ctx context.Context, email string) (User, error) {
	row := q.db.QueryRowContext(ctx, getUserByEmail, email)
	var i User
	err := row.Scan(
		&i.ID,
		&i.FirstName,
		&i.LastName,
		&i.Dob,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Email,
		&i.HasedPassword,
	)
	return i, err
}

const reset = `-- name: Reset :exec
DELETE FROM users
`

func (q *Queries) Reset(ctx context.Context) error {
	_, err := q.db.ExecContext(ctx, reset)
	return err
}

const updatePassword = `-- name: UpdatePassword :exec
UPDATE users
SET hased_password = $2, updated_at = NOW()
WHERE id = $1
`

type UpdatePasswordParams struct {
	ID            uuid.UUID
	HasedPassword string
}

func (q *Queries) UpdatePassword(ctx context.Context, arg UpdatePasswordParams) error {
	_, err := q.db.ExecContext(ctx, updatePassword, arg.ID, arg.HasedPassword)
	return err
}

const updateUser = `-- name: UpdateUser :one
UPDATE users
SET first_name = $2, last_name = $3, email = $4,
updated_at = NOW()
WHERE id = $1
RETURNING id, first_name, last_name, dob, created_at, updated_at, email, hased_password
`

type UpdateUserParams struct {
	ID        uuid.UUID
	FirstName string
	LastName  sql.NullString
	Email     string
}

func (q *Queries) UpdateUser(ctx context.Context, arg UpdateUserParams) (User, error) {
	row := q.db.QueryRowContext(ctx, updateUser,
		arg.ID,
		arg.FirstName,
		arg.LastName,
		arg.Email,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.FirstName,
		&i.LastName,
		&i.Dob,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Email,
		&i.HasedPassword,
	)
	return i, err
}
