name: cd

on:
  push:
    branches: [main]

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: "1.24.2"

      - name: Build app
        run: ./scripts/buildprod.sh

      - name: Log into Docker Hub
        run: echo "${{ secrets.DOCKER_ACCESS_TOKEN }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Build image
        run: docker build . -t "${{ secrets.DOCKER_USERNAME }}"/ar_united:latest

      - name: Push image
        run: docker push "${{ secrets.DOCKER_USERNAME }}"/ar_united:latest

      - name: Render deploy
        run: curl -X POST "${{ secrets.RENDER_DEPLOY_HOOK }}"
